### ISSUE TITLE
Showing output in sidebar instead of a window

### ISSUE THREAD

**Issue by benevolentprof** [bodnaristvan/JavascriptHinter.tmbundle#6]
I have installed the bundle successfully and I'm not trying to get the output to appear in a sidebar instead of a window. There is the instruction to use the string:

```
defaults write com.macromates.TextMate.preview htmlOutputPlacement right
```

But where do put this string? In a file somewhere? Thanks.

**Comment by bodnaristvan** [comment]
(guess i'm a bit late to the party, but maybe it'll help others..)
You have to enter that command into the terminal, it needs to be run only once, the setting will be saved.
